name: Backend CI

on:
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  push:
    branches: [ main ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
jobs:
  backend-cheks:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Print event type
        run: echo "Event:${{ github.event_name }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Sync dependencies
        run: uv sync

      - name: Ruff (lint)
        run: uv run ruff check .

      - name: Pytest
        run: uv run pytest

      - name: Mypy
        run: uv run mypy app